### ISSUE TITLE
kg_resources.ResolutionError: No script named 'pokemon'

### ISSUE THREAD

**Issue by dwedaz** [LazoCoder/Pokemon-Terminal#136]
Hi i am trying to install on my osx sierra
using this methodDistutils (System-wide)
I clone the repo, and run `sudo python setup.py` install at the root of the repo.
install successfully but when i run pokemon i got some error
```

Traceback (most recent call last):
  File "/usr/local/bin/pokemon", line 4, in <module>
    __import__('pkg_resources').run_script('pokemon-terminal==1.1.0', 'pokemon')
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'pokemon'
```

**Comment by dwedaz** [comment]
i deciede to use pip3 installation and got some error but fixed by this instruction:

If you get the error 39:46: syntax error: Expected end of line but found identifier. (-2741): Locate the file ITerm.py in pokemonterminal/adapter/implementations and on line 7, change iTerm to iTerm2. If you still experience the error, try changing it to iTerm 2.
