### ISSUE TITLE
npm install, is-fullwidth-code-point missing

### ISSUE THREAD

**Issue by SevereOverfl0w** [LazoCoder/Pokemon-Terminal#153]
```
❯ sudo npm install --global pokemon-terminal
module.js:545
    throw err;
    ^
Error: Cannot find module 'is-fullwidth-code-point'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/string-width/index.js:4:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by sylveon** [comment]
Sounds like your npm install is broken

**Comment by SevereOverfl0w** [comment]
Today, this works. Can't explain it.
