### ISSUE TITLE
Error when starting a slideshow with the 'dark' filter

### ISSUE THREAD

**Issue by HotelCalifornia** [LazoCoder/Pokemon-Terminal#159]
as far as I've been able to tell, this doesn't happen with any other filters. example output below

```
C:\cmder
λ pokemon -ss 0.05 -d 0.2
Starting slideshow with 10 Pokemons and a delay of 0.05 minutes.
Forked process to background with PID 18540.
You can stop it with 'pokemon -c'.

C:\cmder
λ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\akbro\appdata\local\programs\python\python36-32\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\akbro\appdata\local\programs\python\python36-32\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

**Comment by LazoCoder** [comment]
The npm package was out-dated. It has been updated so it should be good now.

**Comment by HotelCalifornia** [comment]
Sorry, I should have specified that this is an issue with the pip package (version 1.2.0)
