### ISSUE TITLE
Syntax Error in Ubuntu 16.04 LTS Xenial

### ISSUE THREAD

**Issue by kish-shuks** [LazoCoder/Pokemon-Terminal#199]
cc1:~$pokemon pidgey
Traceback (most recent call last):
  File "/home/kishan/.local/bin/pokemon", line 33, in <module>
    sys.exit(load_entry_point('pokemon-terminal==1.3.0', 'console_scripts', 'pokemon')())
  File "/home/kishan/.local/bin/pokemon", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/kishan/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/kishan/.local/lib/python3.5/site-packages/pokemonterminal/main.py", line 62
    print(f"#{pkmn.get_id()} - {pkmn.get_name().title()}")
                                                        ^
SyntaxError: invalid syntax

**Comment by sylveon** [comment]
You need at least python 3.6. you're using Python 3.5.
