### ISSUE TITLE
ValueError: '=' alignment not allowed in string format specifier

### ISSUE THREAD

**Issue by davjd** [LazoCoder/Pokemon-Terminal#49]
I get this error when calling pokemon and a parameter:
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daaaavid/.Pokemon-Terminal/pokemon", line 246, in <module>
    single_argument_handler(argv[1].lower())
  File "/home/daaaavid/.Pokemon-Terminal/pokemon", line 172, in single_argument_handler
    db = Database()
  File "/home/daaaavid/.Pokemon-Terminal/database.py", line 51, in __init__
    self.__load_data()
  File "/home/daaaavid/.Pokemon-Terminal/database.py", line 161, in __load_data
    identifier = '{:03}'.format(identifier)
ValueError: '=' alignment not allowed in string format specifier

---------------------------------------------------------------------------------------

I even get this when calling the help parameter.

**Comment by LazoCoder** [comment]
Should be fixed now. Thanks for bringing this issue up.

**Comment by LazoCoder** [comment]
It looks like the most recent commits created some issues. I'm gonna have to roll them back, sorry for the inconvenience.

**Comment by LazoCoder** [comment]
Should be good now.
